Repository Green-Software-Foundation/if, pull requests merged in 2023-11, with the labels that each got.

#220 Azure importer model
  .env.example
  .gitignore
  examples/impls/test/azure.yml
  examples/ompls/azure.yml
  package.json
  src/__mocks__/azure/index.ts
  src/__tests__/unit/lib/azure-importer/index.test.ts
  src/__tests__/unit/util/args.test.ts
  src/__tests__/unit/util/models-universe.test.ts
  src/__tests__/unit/util/observatory.test.ts
  src/__tests__/unit/util/supercomputer.test.ts
  src/__tests__/unit/util/yaml.test.ts
  src/config/config.ts
  src/lib/azure-importer/index.ts
  src/lib/index.ts
  src/lib/sci/index.test.ts
  src/types/azure-importer.ts
  src/util/models-universe.ts
  src/util/observatory.ts
  toto.yaml
  tsconfig.json
  yarn.lock
Labels: feature, model

#251 models: add time sync method to azure importer
  src/__tests__/unit/lib/azure-importer/index.test.ts
  src/lib/azure-importer/index.ts
Labels: model

#254 Azure input enrichment
  examples/impls/test/if-demo.yml
  src/__tests__/unit/lib/azure-importer/index.test.ts
  src/lib/azure-importer/index.ts
  src/lib/cloud-instance-metadata/index.ts
Labels: model

#174 TDP Finder based on a Kaggle Dataset
  docs/implementations/tdp-finder.md
  examples/impls/tdp-finder-test.yml
  src/__tests__/unit/lib/tdp-finder/index.test.ts
  src/config/config.ts
  src/lib/index.ts
  src/lib/tdp-finder/README.md
  src/lib/tdp-finder/boavizta_data.csv
  src/lib/tdp-finder/data.csv
  src/lib/tdp-finder/data2.csv
  src/lib/tdp-finder/index.ts
Labels: feature

#276 Create general purpose developer issue template
  .github/ISSUE_TEMPLATE/dev-ticket.md
Labels: project-management

#278 Create sprint-retro issue template
  .github/ISSUE_TEMPLATE/sprint-retro.md
Labels: project-management

#277 Create sprint-planning issue template
  .github/ISSUE_TEMPLATE/sprint-planning.md
Labels: project-management

#275 Create bug-report.md issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: project-management

#285 Update dev-ticket.md
  .github/ISSUE_TEMPLATE/dev-ticket.md
Labels: bug, documentation
