Repository Green-Software-Foundation/if, pull requests merged in 2024-03, with the labels that each got.

#495 Add refactor migration guide
  README.md
  Refactor-migration-guide.md
Labels: documentation

#512 Add rimraf to build script
  package.json
Labels: bug

#521 fix(config): add missing params to params.ts
  Refactor-migration-guide.md
  examples/manifests/asim-demo.yml
  examples/manifests/generics.yml
  examples/manifests/group-by.yml
  examples/manifests/mock-observation.yml
  examples/manifests/nesting.yml
  examples/manifests/pipeline-demo-1.yml
  examples/manifests/pipeline-demo-2.yml
  examples/manifests/pipeline-demo.yml
  examples/manifests/pipeline-teads-sci.yml
  examples/manifests/pipeline-with-generics.yml
  examples/manifests/pipeline-with-mocks.yml
  src/config/params.ts
Labels: bug, cli

#522 Add missing metadata params to params.ts
  src/config/params.ts
Labels: bug, cli

#534 Update README docs for builtins
  src/builtins/README.md
Labels: documentation

#556 Clarify contribution expectations for hackathon in readme and contributing.md
  CONTRIBUTING.md
  README.md
Labels: documentation, high-priority, size: small, awaiting-dev-review

#557 Builtins unit test
  src/__mocks__/builtins/export-csv.ts
  src/__tests__/unit/builtins/export-csv-raw.test.ts
  src/__tests__/unit/builtins/export-csv.test.ts
  src/__tests__/unit/builtins/export-log.test.ts
  src/__tests__/unit/builtins/export-yaml.test.ts
  src/__tests__/unit/builtins/group-by.test.ts
  src/__tests__/unit/builtins/time-sync.test.ts
  src/builtins/export-csv-raw.ts
  src/builtins/export-csv.ts
  src/builtins/group-by.ts
  src/builtins/time-sync.ts
Labels: awaiting-dev-review

#558 Parameterize unit tests
  src/__mocks__/fs/index.ts
  src/__tests__/unit/lib/load.test.ts
Labels: awaiting-dev-review

#550 Add github processes doc to IF repo
  github-processes.md
Labels: project-management

#561 Initalize tests
  src/__mocks__/plugin/index.ts
  src/__mocks__/plugin/lib/index.ts
  src/__mocks__/plugin/lib/mockavizta/index.ts
  src/__tests__/unit/lib/initalize.test.ts
Labels: tests, medium-priority, size: medium, dev-review-pass, qa-pass

#563 Aggregate tests
  src/__tests__/unit/lib/aggregate.test.ts
Labels: tests, medium-priority, size: medium, dev-review-pass, qa-pass

#564 Time-sync test coverage
  src/__tests__/unit/builtins/time-sync.test.ts
Labels: tests, medium-priority, size: medium, dev-review-pass, qa-pass, fix

#516 optimize merge defaults strategy
  package-lock.json
  src/__tests__/unit/util/helpers.test.ts
  src/lib/compute.ts
  src/util/helpers.ts
Labels: feature, medium-priority, size: medium, dev-review-pass, awaiting-qa
