Repository Green-Software-Foundation/if, pull requests merged in 2024-04, with the labels that each got.

#565 Compute tests
  src/__tests__/unit/lib/compute.test.ts
  src/index.ts
  src/lib/compute.ts
  src/types/compute.ts
Labels: tests, medium-priority, size: medium, awaiting-dev-review, qa-pass, fix

#578 Add unit test for args.ts
  src/__tests__/unit/util/args.test.ts
Labels: tests, size: small, awaiting-dev-review

#573 Fix manifests
  examples/manifests/boavizta-pipeline.yml
  examples/manifests/cim.yml
  examples/manifests/cloud-metadata-teads.yml
  examples/manifests/cloud-metadata.yml
  examples/manifests/e-net.yml
  examples/manifests/generics.yml
  examples/manifests/group-by.yml
  examples/manifests/nesting.yml
  examples/manifests/pipeline-demo-1.yml
  examples/manifests/pipeline-demo-2.yml
  examples/manifests/pipeline-demo.yml
  examples/manifests/pipeline-teads-sci.yml
  examples/manifests/pipeline-with-generics.yml
  examples/manifests/pipeline-with-mocks.yml
  examples/manifests/teads-aws.yml
  examples/manifests/watt-time.yml
  src/builtins/README.md
Labels: documentation, size: large, dev-review-pass, awaiting-qa, fix

#596 chore(package): release v0.3.2 ✨
  package-lock.json
  package.json
Labels: release

#597 Release v0.3.2
  CONTRIBUTING.md
  README.md
  examples/manifests/boavizta-pipeline.yml
  examples/manifests/cim.yml
  examples/manifests/cloud-metadata-teads.yml
  examples/manifests/cloud-metadata.yml
  examples/manifests/e-net.yml
  examples/manifests/generics.yml
  examples/manifests/group-by.yml
  examples/manifests/nesting.yml
  examples/manifests/pipeline-demo-1.yml
  examples/manifests/pipeline-demo-2.yml
  examples/manifests/pipeline-demo.yml
  examples/manifests/pipeline-teads-sci.yml
  examples/manifests/pipeline-with-generics.yml
  examples/manifests/pipeline-with-mocks.yml
  examples/manifests/teads-aws.yml
  examples/manifests/watt-time.yml
  github-processes.md
  package-lock.json
  package.json
  src/__mocks__/builtins/export-csv.ts
  src/__mocks__/fs/index.ts
  src/__mocks__/plugin/index.ts
  src/__mocks__/plugin/lib/index.ts
  src/__mocks__/plugin/lib/mockavizta/index.ts
  src/__tests__/unit/builtins/export-csv-raw.test.ts
  src/__tests__/unit/builtins/export-csv.test.ts
  src/__tests__/unit/builtins/export-log.test.ts
  src/__tests__/unit/builtins/export-yaml.test.ts
  src/__tests__/unit/builtins/group-by.test.ts
  src/__tests__/unit/builtins/time-sync.test.ts
  src/__tests__/unit/lib/aggregate.test.ts
  src/__tests__/unit/lib/compute.test.ts
  src/__tests__/unit/lib/initalize.test.ts
  src/__tests__/unit/lib/load.test.ts
  src/__tests__/unit/lib/parameterize.test.ts
  src/__tests__/unit/util/args.test.ts
  src/__tests__/unit/util/helpers.test.ts
  src/builtins/README.md
  src/builtins/export-csv-raw.ts
  src/builtins/export-csv.ts
  src/builtins/group-by.ts
  src/builtins/time-sync.ts
  src/index.ts
  src/lib/compute.ts
  src/lib/load.ts
  src/lib/parameterize.ts
  src/types/compute.ts
  src/util/helpers.ts
Labels: release

#608 Fix Help flag issue
  src/__tests__/unit/util/args.test.ts
  src/index.ts
  src/types/process-args.ts
  src/util/args.ts
Labels: size: medium, awaiting-dev-review, fix

#579 Exhaust unit tests
  src/__tests__/unit/lib/exhaust.test.ts
  src/lib/exhaust.ts
Labels: tests, medium-priority, size: medium, awaiting-qa

#575 Add --stdout flag to CLI params
  README.md
  src/__tests__/integration/scenarios/sci-e.ts
  src/__tests__/unit/builtins/export-log.test.ts
  src/__tests__/unit/lib/exhaust.test.ts
  src/__tests__/unit/util/args.test.ts
  src/builtins/export-log.ts
  src/config/config.ts
  src/index.ts
  src/lib/exhaust.ts
  src/types/process-args.ts
  src/util/args.ts
Labels: feature, medium-priority, size: small, dev-review-pass, awaiting-qa

#642 update dev ticket template
  .github/ISSUE_TEMPLATE/dev-ticket.md
Labels: project-management, high-priority, size: small, epic: QA

#664 Remove carbon hack banner from readme
  CONTRIBUTING.md
  README.md
Labels: documentation

#667 remove redundant issue templates and update agenda template
  .github/ISSUE_TEMPLATE/agenda.md
  .github/ISSUE_TEMPLATE/blank-issue.md
  .github/ISSUE_TEMPLATE/feedback.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: project-management

#663 Add bug triage docs
  CONTRIBUTING.md
  README.md
Labels: documentation, epic: QA
