Repository Green-Software-Foundation/if, pull requests merged in 2024-05, with the labels that each got.

#688 Add project update template
  .github/ISSUE_TEMPLATE/project-updates.md
  .github/ISSUE_TEMPLATE/sprint-planning.md
  .github/ISSUE_TEMPLATE/sprint-retro.md
Labels: project-management

#662 Add release instructions to processes doc
  github-processes.md
Labels: documentation, epic: QA

#665 Env data in output
  package-lock.json
  src/__mocks__/fs/index.ts
  src/__tests__/unit/lib/environment.test.ts
  src/__tests__/unit/lib/load.test.ts
  src/__tests__/unit/util/json.test.ts
  src/__tests__/unit/util/os-checker.test.ts
  src/index.ts
  src/lib/environment.ts
  src/lib/load.ts
  src/types/environment.ts
  src/types/manifest.ts
  src/util/errors.ts
  src/util/helpers.ts
  src/util/os-checker.ts
Labels: feature, size: medium

#697 introduce CLI aliases
  src/__tests__/unit/config/strings.test.ts
  src/__tests__/unit/util/args.test.ts
  src/config/config.ts
  src/config/strings.ts
  src/index.ts
  src/types/process-args.ts
  src/util/args.ts
Labels: feature, awaiting-dev-review

#708 chore(doc): updated readme with shortcuts info
  README.md
Labels: documentation

#691 Dump logs errors
  src/__mocks__/builtins/export-csv.ts
  src/__tests__/unit/builtins/export-csv-raw.test.ts
  src/__tests__/unit/builtins/export-csv.test.ts
  src/__tests__/unit/builtins/export-yaml.test.ts
  src/__tests__/unit/lib/compute.test.ts
  src/__tests__/unit/lib/exhaust.test.ts
  src/__tests__/unit/lib/initialize.test.ts
  src/__tests__/unit/lib/load.test.ts
  src/builtins/export-csv-raw.ts
  src/builtins/export-csv.ts
  src/builtins/export-yaml.ts
  src/index.ts
  src/lib/environment.ts
  src/lib/exhaust.ts
  src/lib/initialize.ts
  src/lib/load.ts
  src/types/manifest.ts
  src/util/errors.ts
  src/util/validations.ts
Labels: feature, epic: QA

#712 CI/CD workflows: change `master` branch to `main`
  .github/workflows/release-commit.yml
  .github/workflows/release-publish.yml
Labels: awaiting-dev-review, fix

#718 Tune release commit workflow to create PR
  .github/workflows/release-commit.yml
Labels: fix

#704 Migrate `sci` plugin to `builtins`
  src/__tests__/unit/builtins/sci.test.ts
  src/__tests__/unit/builtins/time-sync.test.ts
  src/builtins/index.ts
  src/builtins/sci/README.md
  src/builtins/sci/config.ts
  src/builtins/sci/index.ts
  src/types/common.ts
  src/types/helpers.ts
  src/util/helpers.ts
  src/util/validations.ts
Labels: feature, awaiting-dev-review

#696 Migrate `sci-m` to builtins as `sci-embodied`
  manifests/plugins/sci-embodied/failure-invalid-default-emission-value.yml
  manifests/plugins/sci-embodied/success.yml
  src/__tests__/unit/builtins/sci-embodied.test.ts
  src/builtins/index.ts
  src/builtins/sci-embodied/README.md
  src/builtins/sci-embodied/index.ts
  src/types/interface.ts
Labels: feature, size: medium, epic: QA, qa

#645 Move the `sum` plugin into builtins
  manifests/plugins/sum/success.yml
  src/__tests__/unit/builtins/sum.test.ts
  src/builtins/index.ts
  src/builtins/sum/README.md
  src/builtins/sum/index.ts
  src/builtins/sum/types.ts
  src/util/errors.ts
Labels: size: medium, awaiting-dev-review, epic: QA

#709 Migrate `multiply` plugin to `builtins`
  manifests/examples/generics.yml
  manifests/examples/mock-cpu-util-to-carbon.yml
  manifests/plugins/multiply/failure-input-parameter-is-missing.yml
  src/__tests__/unit/builtins/multiply.test.ts
  src/builtins/index.ts
  src/builtins/multiply/README.md
  src/builtins/multiply/index.ts
  src/builtins/multiply/types.ts
  src/util/helpers.ts
Labels: feature

#646 Move the `coefficient` plugin into builtins
  manifests/bugs/azure-importer-ignoring-defaults.yml
  manifests/bugs/azure-importer-incorrect-calculation.yml
  manifests/examples/generics.yml
  manifests/plugins/coefficient/failure-invalid-config-input-param.yml
  manifests/plugins/coefficient/failure-output-param-is-null.yaml
  manifests/plugins/coefficient/success.yml
  src/__tests__/unit/builtins/coefficient.test.ts
  src/builtins/coefficient/README.md
  src/builtins/coefficient/index.ts
  src/builtins/coefficient/types.ts
  src/builtins/index.ts
Labels: size: medium, awaiting-dev-review, epic: QA

#723 Migrate `subtract` from `if-plugins` to `builtins`
  src/__tests__/unit/builtins/subtract.test.ts
  src/builtins/index.ts
  src/builtins/subtract/README.md
  src/builtins/subtract/index.ts
  src/builtins/subtract/types.ts
Labels: feature

#647 Move the `divide` plugin into builtins
  manifests/integrations/cloud-metadata-divide-boavizta.yml
  manifests/plugins/divide/failure-denominator-equal-zero.yml
  manifests/plugins/divide/failure-invalid-config-denominator.yml
  manifests/plugins/divide/failure-missing-numerator.yml
  manifests/plugins/divide/success.yml
  src/__tests__/unit/builtins/divide.test.ts
  src/builtins/divide/README.md
  src/builtins/divide/index.ts
  src/builtins/index.ts
Labels: size: medium, awaiting-dev-review, epic: QA

#710 Migrate `mock-observations` to `builtins`
  src/__tests__/unit/builtins/CommonGenerator.test.ts
  src/__tests__/unit/builtins/RandIntGenerator.test.ts
  src/__tests__/unit/builtins/mock-observations.test.ts
  src/builtins/index.ts
  src/builtins/mock-observations/README.md
  src/builtins/mock-observations/helpers/common-generator.ts
  src/builtins/mock-observations/helpers/rand-int-generator.ts
  src/builtins/mock-observations/index.ts
  src/builtins/mock-observations/interfaces/index.ts
  src/builtins/mock-observations/types.ts
  src/types/common.ts
  src/util/helpers.ts
Labels: feature

#732 Create a generic Interpolation plugin
  manifests/plugins/interpolation/interpolation.yml
  package-lock.json
  package.json
  src/__tests__/unit/builtins/interpolation.test.ts
  src/builtins/index.ts
  src/builtins/interpolation/README.md
  src/builtins/interpolation/index.ts
  src/builtins/interpolation/types.ts
  src/util/errors.ts
  src/util/validations.ts
Labels: feature, size: large, qa

#711 implement `If-diff` script
  package.json
  src/__tests__/unit/builtins/export-log.test.ts
  src/__tests__/unit/util/args.test.ts
  src/builtins/export-log.ts
  src/config/config.ts
  src/diff.ts
  src/index.ts
  src/lib/compare.ts
  src/lib/load.ts
  src/lib/parameterize.ts
  src/types/lib/compare.ts
  src/types/process-args.ts
  src/types/util/args.ts
  src/util/args.ts
  src/util/helpers.ts
Labels: feature, qa

#738 Advanced if diff
  package-lock.json
  src/__mocks__/json.ts
  src/__mocks__/readline/index.ts
  src/__tests__/unit/lib/compare.test.ts
  src/__tests__/unit/lib/environment.test.ts
  src/__tests__/unit/lib/load.test.ts
  src/__tests__/unit/util/args.test.ts
  src/__tests__/unit/util/helpers.test.ts
  src/config/strings.ts
  src/index.ts
  src/lib/compare.ts
  src/lib/load.ts
  src/types/lib/compare.ts
  src/util/args.ts
  src/util/helpers.ts
  src/util/validations.ts
Labels: feature, qa

#741 Migrate `shell` model from `if-plugins` to `builtins`
  manifests/plugins/multiply/success.yml
  manifests/plugins/shell/failure-invalid-command.yml
  manifests/plugins/shell/success.yml
  src/__tests__/unit/builtins/shell.test.ts
  src/builtins/index.ts
  src/builtins/shell/README.md
  src/builtins/shell/index.ts
Labels: feature

#743 Simplify logic in SCI plugin
  manifests/examples/nesting.yml
  manifests/examples/pipeline-teads-sci.yml
  manifests/examples/pipeline-with-aggregate.yml
  manifests/examples/pipeline-with-mocks.yml
  manifests/plugins/sci/failure-invalid-config-value.yml
  manifests/plugins/sci/failure-missing-input-param.yml
  manifests/plugins/sci/success.yml
  src/__tests__/unit/builtins/sci.test.ts
  src/builtins/sci/README.md
  src/builtins/sci/index.ts
Labels: feature
