Repository Green-Software-Foundation/if, pull requests merged in 2024-01, with the labels that each got.

#367 readme: update carbon hack banner image with new dates
  hack-banner.png
Labels: documentation

#315 Grafana csv
  grafana/IF_GRAFANA_SETUP.md
  grafana/if_grafana_config.json
  scripts/yaml-to-csv/yaml-to-csv.md
  scripts/yaml-to-csv/yaml-to-csv.py
Labels: model

#379 reference npm over yarn across `if` repo
  .devcontainer/devcontainer.json
  .github/workflows/nodejs-ci.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/index.ts
  yarn.lock
Labels: documentation, high-priority, size: small
